### ISSUE TITLE
Explore how to use mongodb and mongodb driver 

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/task-manager#3]
**Goal**: See how we can use MongoDB driver to attack a MongoDB database.

Figure out how to perform the CRUD operations and manage data successfully

**Tasks**

- [x] import `mongodb` object of off npm `mongodb` module
- [x] Init a MongoClient from `mongodb` object
- [x] Define the connection URL and the database we are connecting to.
- [x] Connect to MongoDB database server using `MongoClient.connect()`
- [x] Insert our first document
- [ ] run node on the file to see the db `task-manager` created, the collection `user` created and the document inserted.
