### ISSUE TITLE
Auto-cropping and image formating

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/task-manager#90]
The system should be able to process the images supplied by the user before we save them. This can be done by using the npm module called sharp. With the sharp module, we will be able to do amazing things like:

1. Resize the images upload by the user
2. Convert the images into a unified type. Here we are going to go with **png's**

**Tasks :** 

- [x] Make clean up work : delete _**avatars**_ and _**images**_ directories in the project
- [x] In the **index.js** file we create a sandbox code to experiment with **multer**, we can go and delete these codes as well
- [x] Head over to the **User** model and inside go the the `toJSON` function. Inside there we place a code to delete avatar data in the User collection
- [x] Install the sharp npm module
- [x] Focus on the POST /users/me/avatar route handler in use in there the sharp module to process the image before saving it
- [x] Change the image type that we serve to png by heading over to the GET /users/:id/avatar handler function and in there change the content-type to **image/png**
