### ISSUE TITLE
Sending Welcome and Cancelation Email

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/task-manager#95]
**Goal**
In this issue we should be able to integrate SendGrid into the Task Manager Application.
When a user creates an account the system should be able to send him a welcome email
Also when a user cancels his account the system should be able to send him an email (asking him why he wants to leave)

**Tasks**

- [x] creating a function called `sendWelcomeEmail` inside the src/emails/accounts js and exports it. The function takes two parameters (_**email**_ and _**name**_). Export the module as an object because we want to export multiple things.
- [x] move the code that is sending the email inside the function `sendWelcomeEmail`. Use the ES6 literal string to use the user name in the message body
- [x] from src/router/user.js , require the account.js module created and call the `sendWelcomeEmail` function passing the user.email and the user.password

We also want the system to send an email to the user when he cancel his registration. The mail might have a message body like "**Good Bye!! Is there anything we can do to keep you onboard**"

**Tasks**

- [x] Setup a new function called `sendGoodByeEmail` for sending an email on cancelation. The function must have the user email and name as argument
- [x] from the src/routers/user.js call the `sendGoodByeEmail` function inside the DELETE /users/me handler function just after the call to the remove function.
